title: Umar Pulavar Tamil Language Centre
url: https://uptlc.moe.edu.sg
favicon: /images/Moe_logo.jpg
colors:
  primary-color: "#336da2"
  secondary-color: "#0c226c"
  media-colors:
    - title: media-color-one
      color: "#f0990f"
    - title: media-color-two
      color: "#ff7f50"
    - title: media-color-three
      color: "#0a2342"
    - title: media-color-four
      color: "#2f2f2f"
    - title: media-color-five
      color: "#00838f"
description: Official school website of Umar Pulavar Tamil Language Centre.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2uldb6hpe0xwq.amplifyapp.com
prod: https://master.d2uldb6hpe0xwq.amplifyapp.com
shareicon: /images/Icons/LOGO2.png
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: highlights
google_analytics_ga4: ""
